### ISSUE TITLE
New examples

### ISSUE THREAD

**Issue by gabofer82** [ForestAdmin/forest-examples#2]
Hi I need the following examples:

If I have:
User -> ProfileA.user_id
User -> ProfileB.user_id

In ForestAdmin I have two views:
ProfileA and ProfileB

I need show each views with multiple User fields...

And same for create Profiles (with User) in only one form..

Thankyou!

**Comment by SeyZ** [comment]
Hey @gabofer82 - I'm sorry but I don't understand your request.

- Which example are you talking about?
- When you say "User -> ProfileA.user_id" and "user -> ProfileB.user_id". Can you explain me exactly your database schema? Not sure if there are different tables, associations, different databases, etc.

Thank you!
