### ISSUE TITLE
express route is not recognized

### ISSUE THREAD

**Issue by eqperes** [ForestAdmin/forest-examples#5]
Hi, 

I used the mongodb "simple" example to create an Express app for Forest. 
But as I created a route to a new Smart Action, my Express app sends a 404 code every time I try to call this Smart Action. 

Can you confirm I just need to add this line to a file inside the `route` folder ?

`router.post('/forest/actions/add-client', liana.ensureAuthenticated, addClient)`

**Comment by SeyZ** [comment]
Hey @eqperes thanks for your issue.

All the routes you declared into the `route` folder in mounted on the `/forest` url namespace.
Check out the `app.js` with the line:

```
app.use('/forest', require('./routes/' + file));
```

So, you just need to remove `/forest` from your URL in your route to handle the call `/forest/actions/add-client` correctly:

```
router.post('/actions/add-client', liana.ensureAuthenticated, addClient)
```
